### PR TITLE
ses, Add bbox to Feature and FeatureCollection.

### PR DESCRIPTION
**Pull request by sebisteiner**

### CODE REVIEW

**Comment by sebisteiner** [comment]
To get the maven build running on my machine I had to make a change to the main `pom.xml`.

CleanShot 2022-02-24 at 15 17 49

I wasn't sure if I should commit this change? (haven't committed it yet)

**Comment by maesenka** [comment]
Everything runs fine on my end with the POM unchanged.

I'd like this to be behind a feature toggle so users can decide for themselves whether they want to serialize a bbox.

**Comment by sebisteiner** [comment]
> Everything runs fine on my end with the POM unchanged.
> 
> I'd like this to be behind a feature toggle so users can decide for themselves whether they want to serialize a bbox.

Thanks for feedback. I will implement the feature toggle.

**Comment by maesenka** [comment]
I finished the implementation. Your work is included in master now.

**Pull request closed without merging**
